// 66 卷中继：只用简体字段 + 英文简称，给前端 books.json 与引用解析共用。
// English short names follow common BibleGateway/SBL conventions.
export const BOOKS = [
  // 旧约 39 卷
  { code: 'GEN', name: '创世记',       abbr: '创',   en: ['Gen', 'Ge', 'Genesis'],            chapters: 50,  testament: 'OT' },
  { code: 'EXO', name: '出埃及记',     abbr: '出',   en: ['Exo', 'Ex', 'Exod', 'Exodus'],     chapters: 40,  testament: 'OT' },
  { code: 'LEV', name: '利未记',       abbr: '利',   en: ['Lev', 'Lv', 'Leviticus'],          chapters: 27,  testament: 'OT' },
  { code: 'NUM', name: '民数记',       abbr: '民',   en: ['Num', 'Nu', 'Numbers'],            chapters: 36,  testament: 'OT' },
  { code: 'DEU', name: '申命记',       abbr: '申',   en: ['Deu', 'Dt', 'Deut', 'Deuteronomy'], chapters: 34, testament: 'OT' },
  { code: 'JOS', name: '约书亚记',     abbr: '书',   en: ['Jos', 'Josh', 'Joshua'],           chapters: 24,  testament: 'OT' },
  { code: 'JDG', name: '士师记',       abbr: '士',   en: ['Jdg', 'Judg', 'Judges'],           chapters: 21,  testament: 'OT' },
  { code: 'RUT', name: '路得记',       abbr: '得',   en: ['Rut', 'Ru', 'Ruth'],               chapters: 4,   testament: 'OT' },
  { code: '1SA', name: '撒母耳记上',   abbr: '撒上', en: ['1Sa', '1Sam', '1Samuel'],          chapters: 31,  testament: 'OT' },
  { code: '2SA', name: '撒母耳记下',   abbr: '撒下', en: ['2Sa', '2Sam', '2Samuel'],          chapters: 24,  testament: 'OT' },
  { code: '1KI', name: '列王纪上',     abbr: '王上', en: ['1Ki', '1Kgs', '1Kings'],           chapters: 22,  testament: 'OT' },
  { code: '2KI', name: '列王纪下',     abbr: '王下', en: ['2Ki', '2Kgs', '2Kings'],           chapters: 25,  testament: 'OT' },
  { code: '1CH', name: '历代志上',     abbr: '代上', en: ['1Ch', '1Chr', '1Chronicles'],      chapters: 29,  testament: 'OT' },
  { code: '2CH', name: '历代志下',     abbr: '代下', en: ['2Ch', '2Chr', '2Chronicles'],      chapters: 36,  testament: 'OT' },
  { code: 'EZR', name: '以斯拉记',     abbr: '拉',   en: ['Ezr', 'Ezra'],                     chapters: 10,  testament: 'OT' },
  { code: 'NEH', name: '尼希米记',     abbr: '尼',   en: ['Neh', 'Nehemiah'],                 chapters: 13,  testament: 'OT' },
  { code: 'EST', name: '以斯帖记',     abbr: '斯',   en: ['Est', 'Esth', 'Esther'],           chapters: 10,  testament: 'OT' },
  { code: 'JOB', name: '约伯记',       abbr: '伯',   en: ['Job', 'Jb'],                       chapters: 42,  testament: 'OT' },
  { code: 'PSA', name: '诗篇',         abbr: '诗',   en: ['Psa', 'Ps', 'Psalm', 'Psalms'],    chapters: 150, testament: 'OT' },
  { code: 'PRO', name: '箴言',         abbr: '箴',   en: ['Pro', 'Pr', 'Prov', 'Proverbs'],   chapters: 31,  testament: 'OT' },
  { code: 'ECC', name: '传道书',       abbr: '传',   en: ['Ecc', 'Eccl', 'Ecclesiastes'],     chapters: 12,  testament: 'OT' },
  { code: 'SNG', name: '雅歌',         abbr: '歌',   en: ['Sng', 'SS', 'Song', 'Songs'],      chapters: 8,   testament: 'OT' },
  { code: 'ISA', name: '以赛亚书',     abbr: '赛',   en: ['Isa', 'Isaiah'],                   chapters: 66,  testament: 'OT' },
  { code: 'JER', name: '耶利米书',     abbr: '耶',   en: ['Jer', 'Jeremiah'],                 chapters: 52,  testament: 'OT' },
  { code: 'LAM', name: '耶利米哀歌',   abbr: '哀',   en: ['Lam', 'Lamentations'],             chapters: 5,   testament: 'OT' },
  { code: 'EZK', name: '以西结书',     abbr: '结',   en: ['Ezk', 'Eze', 'Ezek', 'Ezekiel'],   chapters: 48,  testament: 'OT' },
  { code: 'DAN', name: '但以理书',     abbr: '但',   en: ['Dan', 'Daniel'],                   chapters: 12,  testament: 'OT' },
  { code: 'HOS', name: '何西阿书',     abbr: '何',   en: ['Hos', 'Hosea'],                    chapters: 14,  testament: 'OT' },
  { code: 'JOL', name: '约珥书',       abbr: '珥',   en: ['Jol', 'Joel'],                     chapters: 3,   testament: 'OT' },
  { code: 'AMO', name: '阿摩司书',     abbr: '摩',   en: ['Amo', 'Am', 'Amos'],               chapters: 9,   testament: 'OT' },
  { code: 'OBA', name: '俄巴底亚书',   abbr: '俄',   en: ['Oba', 'Ob', 'Obad', 'Obadiah'],    chapters: 1,   testament: 'OT' },
  { code: 'JON', name: '约拿书',       abbr: '拿',   en: ['Jon', 'Jonah'],                    chapters: 4,   testament: 'OT' },
  { code: 'MIC', name: '弥迦书',       abbr: '弥',   en: ['Mic', 'Micah'],                    chapters: 7,   testament: 'OT' },
  { code: 'NAM', name: '那鸿书',       abbr: '鸿',   en: ['Nam', 'Nah', 'Nahum'],             chapters: 3,   testament: 'OT' },
  { code: 'HAB', name: '哈巴谷书',     abbr: '哈',   en: ['Hab', 'Habakkuk'],                 chapters: 3,   testament: 'OT' },
  { code: 'ZEP', name: '西番雅书',     abbr: '番',   en: ['Zep', 'Zeph', 'Zephaniah'],        chapters: 3,   testament: 'OT' },
  { code: 'HAG', name: '哈该书',       abbr: '该',   en: ['Hag', 'Haggai'],                   chapters: 2,   testament: 'OT' },
  { code: 'ZEC', name: '撒迦利亚书',   abbr: '亚',   en: ['Zec', 'Zech', 'Zechariah'],        chapters: 14,  testament: 'OT' },
  { code: 'MAL', name: '玛拉基书',     abbr: '玛',   en: ['Mal', 'Malachi'],                  chapters: 4,   testament: 'OT' },
  // 新约 27 卷
  { code: 'MAT', name: '马太福音',     abbr: '太',   en: ['Mat', 'Mt', 'Matt', 'Matthew'],    chapters: 28,  testament: 'NT' },
  { code: 'MRK', name: '马可福音',     abbr: '可',   en: ['Mrk', 'Mk', 'Mark'],               chapters: 16,  testament: 'NT' },
  { code: 'LUK', name: '路加福音',     abbr: '路',   en: ['Luk', 'Lk', 'Luke'],               chapters: 24,  testament: 'NT' },
  { code: 'JHN', name: '约翰福音',     abbr: '约',   en: ['Jhn', 'Jn', 'John'],               chapters: 21,  testament: 'NT' },
  { code: 'ACT', name: '使徒行传',     abbr: '徒',   en: ['Act', 'Acts'],                     chapters: 28,  testament: 'NT' },
  { code: 'ROM', name: '罗马书',       abbr: '罗',   en: ['Rom', 'Romans'],                   chapters: 16,  testament: 'NT' },
  { code: '1CO', name: '哥林多前书',   abbr: '林前', en: ['1Co', '1Cor', '1Corinthians'],     chapters: 16,  testament: 'NT' },
  { code: '2CO', name: '哥林多后书',   abbr: '林后', en: ['2Co', '2Cor', '2Corinthians'],     chapters: 13,  testament: 'NT' },
  { code: 'GAL', name: '加拉太书',     abbr: '加',   en: ['Gal', 'Galatians'],                chapters: 6,   testament: 'NT' },
  { code: 'EPH', name: '以弗所书',     abbr: '弗',   en: ['Eph', 'Ephesians'],                chapters: 6,   testament: 'NT' },
  { code: 'PHP', name: '腓立比书',     abbr: '腓',   en: ['Php', 'Phil', 'Philippians'],      chapters: 4,   testament: 'NT' },
  { code: 'COL', name: '歌罗西书',     abbr: '西',   en: ['Col', 'Colossians'],               chapters: 4,   testament: 'NT' },
  { code: '1TH', name: '帖撒罗尼迦前书', abbr: '帖前', en: ['1Th', '1Thess', '1Thessalonians'], chapters: 5, testament: 'NT' },
  { code: '2TH', name: '帖撒罗尼迦后书', abbr: '帖后', en: ['2Th', '2Thess', '2Thessalonians'], chapters: 3, testament: 'NT' },
  { code: '1TI', name: '提摩太前书',   abbr: '提前', en: ['1Ti', '1Tim', '1Timothy'],         chapters: 6,   testament: 'NT' },
  { code: '2TI', name: '提摩太后书',   abbr: '提后', en: ['2Ti', '2Tim', '2Timothy'],         chapters: 4,   testament: 'NT' },
  { code: 'TIT', name: '提多书',       abbr: '多',   en: ['Tit', 'Titus'],                    chapters: 3,   testament: 'NT' },
  { code: 'PHM', name: '腓利门书',     abbr: '门',   en: ['Phm', 'Phlm', 'Philemon'],         chapters: 1,   testament: 'NT' },
  { code: 'HEB', name: '希伯来书',     abbr: '来',   en: ['Heb', 'Hebrews'],                  chapters: 13,  testament: 'NT' },
  { code: 'JAS', name: '雅各书',       abbr: '雅',   en: ['Jas', 'James'],                    chapters: 5,   testament: 'NT' },
  { code: '1PE', name: '彼得前书',     abbr: '彼前', en: ['1Pe', '1Pet', '1Peter'],           chapters: 5,   testament: 'NT' },
  { code: '2PE', name: '彼得后书',     abbr: '彼后', en: ['2Pe', '2Pet', '2Peter'],           chapters: 3,   testament: 'NT' },
  { code: '1JN', name: '约翰一书',     abbr: '约一', en: ['1Jn', '1John'],                    chapters: 5,   testament: 'NT' },
  { code: '2JN', name: '约翰二书',     abbr: '约二', en: ['2Jn', '2John'],                    chapters: 1,   testament: 'NT' },
  { code: '3JN', name: '约翰三书',     abbr: '约三', en: ['3Jn', '3John'],                    chapters: 1,   testament: 'NT' },
  { code: 'JUD', name: '犹大书',       abbr: '犹',   en: ['Jud', 'Jude'],                     chapters: 1,   testament: 'NT' },
  { code: 'REV', name: '启示录',       abbr: '启',   en: ['Rev', 'Revelation'],               chapters: 22,  testament: 'NT' },
]
