// 读 ../data/cunps/books/*.json，把每章拆成 public/bible/<CODE>/<NN>.json，
// 并产出 public/bible/books.json（只含简体字段）。
import { readFileSync, writeFileSync, mkdirSync, rmSync, existsSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import { BOOKS } from './books-meta.mjs'

const __dirname = dirname(fileURLToPath(import.meta.url))
const ROOT = resolve(__dirname, '..')
const SRC = resolve(ROOT, '..', 'data', 'cunps', 'books')
const OUT = resolve(ROOT, 'public', 'bible')

if (existsSync(OUT)) rmSync(OUT, { recursive: true, force: true })
mkdirSync(OUT, { recursive: true })

// 注：上游错字订正在 cunps.py fetch 步骤就已写入 data/cunps/books/*.json
// （见根目录 corrections.py），所以此处纯透传，不再做替换。

let totalChapters = 0
let totalVerses = 0

for (const meta of BOOKS) {
  const srcPath = join(SRC, `${meta.code}.json`)
  const raw = JSON.parse(readFileSync(srcPath, 'utf8'))
  if (raw.chapters_data.length !== meta.chapters) {
    throw new Error(`${meta.code} chapter count mismatch: meta=${meta.chapters} data=${raw.chapters_data.length}`)
  }
  const bookDir = join(OUT, meta.code)
  mkdirSync(bookDir, { recursive: true })
  for (const ch of raw.chapters_data) {
    const verses = ch.verses.map((v) => ({ n: v.sec, t: v.text }))
    const nn = String(ch.chapter).padStart(2, '0')
    writeFileSync(join(bookDir, `${nn}.json`), JSON.stringify({ v: verses }))
    totalChapters += 1
    totalVerses += verses.length
  }
}

const booksOut = BOOKS.map((b) => ({
  code: b.code,
  name: b.name,
  abbr: b.abbr,
  en: b.en,
  chapters: b.chapters,
  testament: b.testament,
}))
writeFileSync(join(OUT, 'books.json'), JSON.stringify(booksOut))

// 同步生成 lib/generated/books.ts，供前端 bundle 直接 import（reference 解析、首页网格）
const GEN_DIR = resolve(ROOT, 'lib', 'generated')
mkdirSync(GEN_DIR, { recursive: true })
const ts = `// AUTO-GENERATED by scripts/export-data.mjs — do not edit by hand.
export type Testament = 'OT' | 'NT'

export interface BookMeta {
  code: string
  name: string
  abbr: string
  en: string[]
  chapters: number
  testament: Testament
}

export const BOOKS: BookMeta[] = ${JSON.stringify(booksOut, null, 2)}

export const BOOKS_BY_CODE: Record<string, BookMeta> = Object.fromEntries(
  BOOKS.map((b) => [b.code, b]),
)
`
writeFileSync(join(GEN_DIR, 'books.ts'), ts)

console.log(`[export-data] ${BOOKS.length} books, ${totalChapters} chapters, ${totalVerses} verses → ${OUT}`)
